Intrinsics:
  ACCE:
    BIAS:
      r0c0: 0.0
      r1c0: 0.0
      r2c0: 0.0
    MAP_COEFF:
      r0c0: 1.0
      r1c0: 1.0
      r2c0: 1.0
      r3c0: 0.0
      r4c0: 0.0
      r5c0: 0.0
  GYRO:
    BIAS:
      r0c0: 0.0
      r1c0: 0.0
      r2c0: 0.0
    MAP_COEFF:
      r0c0: 1.0
      r1c0: 1.0
      r2c0: 1.0
      r3c0: 0.0
      r4c0: 0.0
      r5c0: 0.0
  SO3_AtoG:
    qx: 0.0
    qy: 0.0
    qz: 0.0
    qw: 1.0